### ISSUE TITLE
Settings don't save despite the game saying they're saving.

### ISSUE THREAD

**Issue by Tenome** [twinaphex/cannonball#20]
Dunno if you're still updating this, but I've encountered a minor issue with my settings not saving properly. Windows 7, latest version of the core. The config.xml (which is in the default RetroArch directory instead of the cannonball folder?) says that my settings are correct, but every time I boot the game, high-res mode is turned off, etc. The desktop version linked below works just fine, so it's something about this core not reading the XML correctly.

Also, if you weren't aware, this fork seems to be better updated since I don't think the original dev is working on this anymore.

https://github.com/J1mbo/cannonball

This desktop version that you can grab pre-compiled here seems to be based on that. It has more features, the credits function works properly, it has the widescreen tilemap, etc.

https://retroreloader.itch.io/outrun86coast

**Comment by Tatsuya79** [comment]
The core is always reading from the core options, not the game menu/xml.
It would need to be modified to allow both, which I couldn't do.
